# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dfd2f3aec72871f3b4a02a4ce439142f"
name = "SectionApp"
handle = "sectionapp-5"
application_url = "https://diabetes-bibliography-vary-ribbon.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testtakewithfood.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://diabetes-bibliography-vary-ribbon.trycloudflare.com/auth/callback",
  "https://diabetes-bibliography-vary-ribbon.trycloudflare.com/auth/shopify/callback",
  "https://diabetes-bibliography-vary-ribbon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
