# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57ff647e2098c60259640fbe98dad2df"
name = "Anti Page Builder"
handle = "anti-page-builder"
application_url = "https://anti-page-builder.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "section-app-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes"

[auth]
redirect_urls = [
  "https://anti-page-builder.onrender.com/auth/callback",
  "https://anti-page-builder.onrender.com/auth/shopify/callback",
  "https://anti-page-builder.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
